# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Run python script
      run: |
        git config user.name "sram055"
        git config user.email "samvi2000@rediffmail.com"
        git checkout master
        cd /home/runner/work/testpy/testpy
        ls -ltr
        git log 
