# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application full

on:
  schedule:
    - cron: '30 14 02 6 2'
   # * is a special character in YAML so you have to quote this string
   #  - cron:  '*/15 * * * *'
   #    # ┌───────────── minute (0 - 59)
   #  │ ┌───────────── hour (0 - 23)
   #   │ │ ┌───────────── day of the month (1 - 31)
   #   │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
   #   │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
   #   │ │ │ │ │                                   
   #   │ │ │ │ │
   #  │ │ │ │ │
    #  * * * * *
    
      
#on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
 #push:
    #branches:
      #- master
      #- sram055-patch-1
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest gitpython
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
    - name: Run python script
      run: |
        git config user.name "sram055"
        git config user.email "samvi2000@rediffmail.com"
        #git fetch --all
        #git log --all --after="2020-05-21 00:00" --before="2020-05-30 23:59" --diff-filter=D --summary | grep 'delete' | awk '{print $4}' 
        python destructiveChanges.py
    
    - name: git push file to origin
      run: |
        git add .
        git commit -m "updating repo with custo.xml"
        git push origin master
        
        
        
