name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: pre-commit/action@v2.0.0

    - name: Run python script
      run: |
        git config user.name "sram055"
        git config user.email "samvi2000@rediffmail.com"
        git fetch --all
        git log --all --after="2020-05-21 00:00" --before="2020-06-21 00:00" --diff-filter=D --summary | grep 'delete' | awk '{print $4}' 
