# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
    - name: Run python script
      run: |
        python mypy.py
    - name: update repo
      run: |
        git config user.name "sram055"
        git config user.email "samvi2000@rediffmail.com"
    - name: git delete check
      run: |
        git log --diff-filter=D --summary      
     
    - name: git push file to origin
      run: |
        git add .
        git commit -m "updating repo with cust.xml"
        git push origin master
        
        
        
